//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPersonenverwaltung.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PersonId { get; set; }
        public string Name { get; set; }
        public string SecondName { get; set; }
        public string Street { get; set; }
        public string Plz { get; set; }
        public string Place { get; set; }
        public int AbteilungAbteilungId { get; set; }
    
        public virtual Abteilung Abteilung { get; set; }
    }
}
